// Auto-generated types for the Earnxact Supabase schema.
// Re-run `npx supabase gen types typescript --project-id <id>` to refresh.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

// ─── Enums ────────────────────────────────────────────────────────────────────

export type PlanCategory = "free" | "basic" | "premium" | "vip";
export type ReferralStatus = "pending" | "active" | "rewarded";
export type WalletTransactionType = "credit" | "debit" | "withdrawal" | "bonus";

// ─── Table Row Types ──────────────────────────────────────────────────────────

export interface UserRow {
  /** UUID primary key — generated by Supabase Auth */
  id: string;
  /** Short human-readable ID, e.g. EXU-A1B2C3 */
  user_id: string;
  username: string;
  first_name: string;
  last_name: string;
  email: string;
  phone_number: string | null;
  avatar_url: string | null;
  /** Bank account holder name */
  account_name: string | null;
  account_number: string | null;
  bank_name: string | null;
  plan_category: PlanCategory;
  referral_code: string;
  /** FK → users.id of the user who invited this user */
  referred_by: string | null;
  check_in_streak: number;
  last_check_in: string | null;
  /** How many daily tasks the user has completed today */
  daily_tasks_completed: number;
  /** Timestamp when daily_tasks_completed resets to 0 */
  daily_tasks_reset_at: string | null;
  is_active: boolean;
  kyc_verified: boolean;
  created_at: string;
  updated_at: string;
}

export interface WalletRow {
  id: string;
  /** FK → users.id */
  user_id: string;
  /** Current spendable balance */
  balance: number;
  /** Lifetime earnings */
  total_earned: number;
  /** Lifetime withdrawals */
  total_withdrawn: number;
  /** Earnings awaiting clearance */
  pending_balance: number;
  currency: string;
  updated_at: string;
}

export interface WalletTransactionRow {
  id: string;
  /** FK → wallets.id */
  wallet_id: string;
  /** FK → users.id */
  user_id: string;
  type: WalletTransactionType;
  amount: number;
  description: string | null;
  reference: string | null;
  created_at: string;
}

export interface ReferralRow {
  id: string;
  /** The user who shared the referral link */
  referrer_id: string;
  /** The user who signed up via that link */
  referred_id: string;
  referral_code: string;
  status: ReferralStatus;
  /** Reward credited to referrer for this specific referral */
  reward_amount: number;
  created_at: string;
  updated_at: string;
}

export interface LeaderboardRow {
  id: string;
  /** FK → users.id */
  user_id: string;
  total_points: number;
  weekly_points: number;
  monthly_points: number;
  /** e.g. "2024-W32" or "2024-08" */
  season: string;
  rank: number | null;
  updated_at: string;
}

// ─── Database shape (for the Supabase client generic) ─────────────────────────

export interface Database {
  public: {
    Tables: {
      users: {
        Row: UserRow;
        Insert: Omit<UserRow, "created_at" | "updated_at"> & Partial<Pick<UserRow, "created_at" | "updated_at">>;
        Update: Partial<Omit<UserRow, "id">>;
      };
      wallets: {
        Row: WalletRow;
        Insert: Omit<WalletRow, "updated_at"> & Partial<Pick<WalletRow, "updated_at">>;
        Update: Partial<Omit<WalletRow, "id" | "user_id">>;
      };
      wallet_transactions: {
        Row: WalletTransactionRow;
        Insert: Omit<WalletTransactionRow, "created_at"> & Partial<Pick<WalletTransactionRow, "created_at">>;
        Update: never;
      };
      referrals: {
        Row: ReferralRow;
        Insert: Omit<ReferralRow, "created_at" | "updated_at"> & Partial<Pick<ReferralRow, "created_at" | "updated_at">>;
        Update: Partial<Omit<ReferralRow, "id">>;
      };
      leaderboard: {
        Row: LeaderboardRow;
        Insert: Omit<LeaderboardRow, "updated_at"> & Partial<Pick<LeaderboardRow, "updated_at">>;
        Update: Partial<Omit<LeaderboardRow, "id" | "user_id">>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      plan_category: PlanCategory;
      referral_status: ReferralStatus;
      wallet_transaction_type: WalletTransactionType;
    };
  };
}
